chore(cockpit): add german translation for 7.16
camunda/camunda-webapp-translations pull request #124
Opened 2021-09-24 15:18 UTC by tasso94

related to CAM-13918

2021-09-24 15:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda/camunda-webapp-translations?pullRequest=124) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/camunda/camunda-webapp-translations?pullRequest=124) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda/camunda-webapp-translations?pullRequest=124) it.</sub>

2021-09-27 12:13 UTC, marstamm approved these changes

2021-09-27 12:14 UTC, marstamm requested changes

2021-09-27 12:14 UTC, marstamm commented on cockpit/de.json
> +    "PLGN_CORRELATE_MSG_NAME": "Message Name",
```suggestion
    "PLGN_CORRELATE_MSG_NAME": "Nachrichtenname",
```

2021-09-27 12:15 UTC, tasso94 commented on cockpit/de.json
> +    "PLGN_CORRELATE_MSG_NAME": "Message Name",
👍

2021-09-27 13:06 UTC, marstamm approved these changes

2021-09-27 13:17 UTC, merged