feat(admin): request platform information
camunda/camunda-webapp-translations pull request #139
Opened 2022-03-08 16:43 UTC by cliftondavies

related to CAM-14068

2022-03-09 12:06 UTC, danielkelemen approved these changes

2022-03-11 10:07 UTC, tasso94 requested changes

2022-03-11 10:07 UTC, tasso94 commented on admin/en.json
> +    "DIAGNOSTICS_INTRODUCTION": "To aid problem diagnosis by enabling customer facing teams to quickly understand the environment/distribution a user is running.",
```suggestion
    "DIAGNOSTICS_INTRODUCTION": "The diagnostics data allows to understand the environment to aid problem diagnosis.",
```
This introduction sounds like a user story from a ticket description but might not make much sense when a user reads it.

2022-03-11 10:07 UTC, tasso94 commented on admin/en.json
> +    "PLGN_MOD_SHOW_REQUEST_PAYLOAD": "View platform data",
```suggestion
```
Do we need this translation string anymore?

2022-03-15 08:21 UTC, tasso94 commented on admin/en.json
> +    "TELEMETRY_FETCH_DATA_ERROR_MESSAGE": "Telemetry data fetching failed:",
```suggestion
    "DIAGNOSTICS_FETCH_DATA_ERROR_MESSAGE": "Telemetry data fetching failed: {{msg}}",
```

2022-03-15 08:39 UTC, tasso94 commented on admin/en.json
> +    "DIAGNOSTICS_FETCH_DATA_ERROR_MESSAGE": "Telemetry data fetching failed: {{msg}}",
I changed the name of the token from `TELEMETRY_FETCH_DATA_ERROR_MESSAGE` to `DIAGNOSTICS_FETCH_DATA_ERROR_MESSAGE`. Also, I added a `msg` placeholder.

2022-03-15 08:39 UTC, tasso94 approved these changes
Looks good to me. Feel free to merge 🙂 👍

2022-03-15 10:05 UTC, merged