Tasklist in Hindi Language
camunda/camunda-webapp-translations pull request #82
Opened 2020-10-07 08:49 UTC by anchal-gupta

Please review tasklist in hindi language and if it works for you, please merge it. If it does not work for you, please let me know discrepancies you find. I will be happy to improve :)

2020-10-07 08:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda/camunda-webapp-translations?pullRequest=82) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/camunda/camunda-webapp-translations?pullRequest=82) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda/camunda-webapp-translations?pullRequest=82) it.</sub>

2020-10-09 09:05 UTC, tmetzke commented
Hey @anchal-gupta,

thanks for that awesome contribution, we appreciate it!

We will have a closer look and provide proper feedback as soon as we can. :+1:

Thanks and best,
Tobias

2020-10-13 07:45 UTC, marstamm requested changes
Hi @anchal-gupta, thank you for you contribution! We appreciate the effort that went into this.

However, there are some technicalities which will prevent the translation from being used. Please make sure that the [translation file works in Tasklist](https://docs.camunda.org/manual/7.14/webapps/tasklist/configuration/#localization) when workin on it.
I added some hints below.

Cheers
Martin

2020-10-13 07:45 UTC, marstamm commented on tasklist/hi.json
> +  " लेबल " : {
The 'labels' property is not a translate string. The translations will not be found by the Application if the top-level attributes are changed

```suggestion
  "labels" : {
```

2020-10-13 07:45 UTC, marstamm commented on tasklist/hi.json
> +    " APP_VENDOR " : " ऐप विक्रेता " ,
The translation label should be without leading or trailing spaces. I can't speak for the translation, please make sure that this is correct as well.

```suggestion
    "APP_VENDOR" : " ऐप विक्रेता " ,
```

This applies to all labels

2020-10-13 07:45 UTC, marstamm commented on tasklist/hi.json
> +    " PAGES_MSG_ENGINE_NOT_EXISTS " : " जिस प्रक्रिया इंजन को आप एक्सेस करने का प्रयास कर रहे हैं वह मौजूद नहीं है , " ।
The delimiter is wrong and the file no longer a valid JSON

```suggestion
    " PAGES_MSG_ENGINE_NOT_EXISTS " : " जिस प्रक्रिया इंजन को आप एक्सेस करने का प्रयास कर रहे हैं वह मौजूद नहीं है , ",
```

2020-10-13 07:45 UTC, marstamm commented on tasklist/hi.json
> +    " CAM_WIDGET_VARIABLES_TABLE_DIALOGUE " : " यकीन है कि आप '{{नाम}}' को हटाना चाहते हैं कर रहे हैं " ,
Placeholders are not translated, as the replacement will no longer work

2020-10-13 07:45 UTC, marstamm commented on tasklist/hi.json
> +    " CAM_WIDGET_VARIABLE_NULL " : " <null> " ,
Please trim the labels
```suggestion
    "CAM_WIDGET_VARIABLE_NULL" : "<null>" ,
```

2020-10-13 07:45 UTC, marstamm commented on tasklist/hi.json
> +    " CAM_WIDGET_STRING_DIALOG_TITLE " : " निरीक्षण \" {{नाम}} \ " चर " ,
Translated Placeholder

2020-10-13 07:45 UTC, marstamm commented on tasklist/hi.json
> +    " CAM_WIDGET_VARIABLES_TABLE_DIALOGUE " : " यकीन है कि आप '{{नाम}}' को हटाना चाहते हैं कर रहे हैं " ,
```suggestion
    "CAM_WIDGET_VARIABLES_TABLE_DIALOGUE" : " यकीन है कि आप '{{name}}' को हटाना चाहते हैं कर रहे हैं " ,
```

2020-10-13 07:45 UTC, marstamm commented on tasklist/hi.json
> +    " महीने " : [
Same as with the 'labels' property, don't translate the property names

```suggestion
  "dateLocales": {
    "months": [
```

2020-10-13 07:45 UTC, marstamm commented on welcome/hi.json
> +    " AUTH_LOGOUT_THANKS " : " आज कैमुंडा का उपयोग करने के लिए धन्यवाद। एक महान {{dayConxtxt}}! " ,।
Broken JSON
```suggestion
    " AUTH_LOGOUT_THANKS " : " आज कैमुंडा का उपयोग करने के लिए धन्यवाद। एक महान {{dayConxtxt}}! " ,
```

2020-10-13 07:45 UTC, marstamm commented on welcome/hi.json
> +  " लेबल " : {
Translated Property

2020-10-13 07:45 UTC, marstamm commented on welcome/hi.json
> +    " CAM_WIDGET_VARIABLE_DIALOG_INSPECT " : " का निरीक्षण चर {{नाम}} " ,
Translated Placeholders

2020-11-09 11:05 UTC, marstamm commented
Hi @anchal-gupta ,

as 2 weeks have passed without updates to the PR, I am going to close it. Feel free to reopen it when you integrated the review hints.

Cheers
Martin

2020-11-09 11:05 UTC, closed without merging